# Generated by Django 4.2.4 on 2023-08-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerposition',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Отдел'),
        ),
    ]
